pipeline{
    agent any
    stages{
        stage("git"){
            steps{
                git credentialsId: 'github', url: 'https://github.com/salmabidh/awsjenkins.git'
            }
            
        }
        stage("build-code"){
              steps{
                 dir("/var/lib/jenkins/workspace/ci-cd-multi_developnment"){
                 
                 sh "mvn clean package"
                 
                 }
                }
              
              }
    }
}